// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSApp.Data;

#nullable disable

namespace POSApp.Data.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20260719120000_AddAssignedByToUsers")]
    partial class AddAssignedByToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("POSApp.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFailedAttempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            FailedAttemptCount = 0,
                            ForcePasswordChange = false,
                            Guid = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsDeleted = false,
                            IsSynced = true,
                            PasswordHash = "$2a$11$BoDXkSEX7DtRJ7klkgHhQ.RpZLtIXZ5dw.Vz/MMreEnMIoYCLa2fu",
                            Role = "Admin",
                            UpdatedAtUtc = new DateTime(2026, 7, 16, 8, 36, 58, 801, DateTimeKind.Utc).AddTicks(443),
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
